version: '3'

services:
  backup:
    image: mazzolino/restic:1.5.0
    container_name: restic-backup
    restart: unless-stopped
    networks:
      - private
    hostname: docker
    volumes:
      - ./volumes:/mnt/volumes
      - ./scripts/wait-for:/usr/local/bin/wait-for:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUN_ON_STARTUP: 'true'
      BACKUP_CRON: '0 30 3 * * *'
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude='*.tmp'
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: ${TIMEZONE}
      # global context, can run anywhere within docker network
      PRE_COMMANDS: |-
        wait-for redis:6379 --timeout=60 -- docker exec redis dump
        wait-for mysql:3306 --timeout=60 -- docker exec mysql dump
      POST_COMMANDS_SUCCESS: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text": "Backup ran successfully!"}'' ${SLACK_NOTIFICATIONS_ENDPOINT}'
      POST_COMMANDS_FAILURE: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text": "Backup failed!"}'' ${SLACK_ALERTS_ENDPOINT}'

  prune:
    image: mazzolino/restic:1.5.0
    container_name: restic-prune
    restart: unless-stopped
    networks:
      - private
    hostname: docker
    environment:
      RUN_ON_STARTUP: 'true'
      PRUNE_CRON: '0 0 4 * * *'
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: ${TIMEZONE}

  check:
    image: mazzolino/restic:1.5.0
    container_name: restic-check
    restart: unless-stopped
    networks:
      - private
    hostname: docker
    environment:
      RUN_ON_STARTUP: 'false'
      CHECK_CRON: '0 15 5 * * *'
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: ${TIMEZONE}

networks:
  private:
    external: true
