version: '3'

services:
  backup:
    image: mazzolino/restic:1
    container_name: restic-backup
    restart: always
    networks:
      - private
    hostname: docker
    volumes:
      - ./volumes:/mnt/volumes
      - ./scripts/wait-for:/usr/local/bin/wait-for
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      RUN_ON_STARTUP: 'true'
      BACKUP_CRON: '0 30 3 * * *'
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude='*.tmp'
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: America/New_York
      PRE_COMMANDS: |-
        wait-for mysql:3306 --timeout=60 -- true
        docker exec mysql /usr/bin/mysqldump -u root --password=mysql-root-password devblog > /mnt/volumes/dumps/devblog-backup.sql
        docker exec mysql /usr/bin/mysqldump -u root --password=mysql-root-password portfolio > /mnt/volumes/dumps/portfolio-backup.sql
      POST_COMMANDS_SUCCESS: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text": "Backup ran successfully!"}'' ${SLACK_NOTIFICATIONS_ENDPOINT}'
      POST_COMMANDS_FAILURE: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text": "Backup failed!"}'' ${SLACK_NOTIFICATIONS_ENDPOINT}'
    labels:
      com.centurylinklabs.watchtower.enable: 'true'

  prune:
    image: mazzolino/restic:1
    container_name: restic-prune
    restart: always
    networks:
      - private
    hostname: docker
    environment:
      RUN_ON_STARTUP: 'true'
      PRUNE_CRON: '0 0 4 * * *'
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: America/New_York
    labels:
      com.centurylinklabs.watchtower.enable: 'true'

  check:
    image: mazzolino/restic:1
    container_name: restic-check
    restart: always
    networks:
      - private
    hostname: docker
    environment:
      RUN_ON_STARTUP: 'false'
      CHECK_CRON: '0 15 5 * * *'
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: America/New_York
    labels:
      com.centurylinklabs.watchtower.enable: 'true'

networks:
  private:
    external: true
