version: '3'

services:
  devblog:
    image: ghost:5.94.0-alpine
    container_name: ghost-devblog
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      # https://github.com/TryGhost/Ghost/issues/11181
      test: "wget --no-verbose --tries=1 --spider --header='X-Forwarded-Proto: https' http://localhost:2368/ghost/api/admin/site/ || exit 1"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - public
      - private
    volumes:
      - ghost-devblog-content:/var/lib/ghost/content
      - ./services/blog/config.json:/var/lib/ghost/config.production.json:ro
    environment:
      url: https://${BLOG_HOST}
      database__connection__user: ghost-devblog
      database__connection__password: ghost-devblog-password
      database__connection__database: devblog
      mail__from: ${SMTP_SENDER}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASS}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.devblog.tls.certresolver: letsencrypt
      traefik.http.routers.devblog.rule: Host(`${BLOG_HOST}`)
      traefik.http.routers.devblog.middlewares: ratelimit-burst@file,ratelimit-window@file
      traefik.http.services.devblog.loadbalancer.server.port: 2368
      flame.type: application
      flame.name: Ghost - Blog
      flame.url: ${BLOG_HOST}
      flame.icon: ghost-outline

networks:
  public: {}
  private: {}

volumes:
  ghost-devblog-content: {}
