version: "3"

services:
  gc:
    image: yelp/docker-custodian:latest
    container_name: gc
    command:
      - --max-container-age
      - 7days
      - --max-image-age
      - 30days
      - --dangling-volumes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
