version: '3'

services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    restart: unless-stopped
    networks:
      - private
    volumes:
      - ./volumes/flame/assets:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PASSWORD: ''
    labels:
      traefik.enable: 'true'
      traefik.http.routers.homepage.rule: Host(`home.janejeon.com`)
      traefik.http.routers.homepage.tls.certresolver: letsencrypt
      # traefik.http.routers.homepage.middlewares: sso-proxy@file
      traefik.http.services.homepage.loadbalancer.server.port: 5005
      com.centurylinklabs.watchtower.enable: 'true'
      com.centurylinklabs.watchtower.monitor-only: 'true'

networks:
  private:
    external: true
