version: '3'

services:
  traefik:
    image: traefik:v2.9.6
    container_name: traefik
    restart: unless-stopped
    command:
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --log.level=INFO
      - --log.format=common
      - --accessLog.format=common
      - --api.dashboard=true
      - --api.insecure=true
      - --entryPoints.http.address=:80
      - --entryPoints.http.http.redirections.entryPoint.to=https
      - --entryPoints.http.http.redirections.entryPoint.scheme=https
      - --entryPoints.http.http.redirections.entryPoint.permanent=true
      - --entryPoints.https.address=:443
      - --entryPoints.https.http.middlewares=gzip@file,no-www@file
      # Trust headers forwarded from Cloudflare to get accurate X-Forwarded-* information:
      # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
      - --entryPoints.https.forwardedHeaders.trustedIPs=${CLOUDFLARE_IPS}
      - --providers.docker.watch=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=public
      - --providers.file.watch=true
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --certificatesResolvers.letsencrypt.acme.email=${SMTP_SENDER}
      - --certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme.json
      # for testing, try https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.letsencrypt.acme.caserver=${ACME_CASERVER:-https://acme-v02.api.letsencrypt.org/directory}
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/traefik:/etc/traefik
      # - ./services/reverse-proxy/traefik.static.yml:/etc/traefik/traefik.yml:ro
      - ./services/reverse-proxy/traefik.dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./volumes/certs:/etc/letsencrypt:ro # docker doesn't really handle symlinks
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      CF_ZONE_API_TOKEN: ${CF_ZONE_API_TOKEN}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.tls.certresolver: letsencrypt
      traefik.http.routers.traefik.rule: Host(`traefik.janejeon.com`)
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.middlewares: sso-proxy@file
      traefik.http.services.api@internal.loadbalancer.server.port: 8080
      flame.type: application
      flame.name: Traefik
      flame.url: traefik.janejeon.com
      flame.icon: routes

networks:
  public:
    external: true
