version: '3'

services:
  traefik:
    image: traefik:v2.6.3
    container_name: traefik
    restart: unless-stopped
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/reverse-proxy/traefik.static.yml:/etc/traefik/traefik.yml:ro
      - ./services/reverse-proxy/traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml:ro
      - ./volumes/certs:/etc/letsencrypt:ro # docker doesn't really handle symlinks
    environment:
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: :443
      TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_MIDDLEWARES: gzip@file,no-www@file
      # Trust headers forwarded from Cloudflare to get accurate X-Forwarded-* information:
      # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
      TRAEFIK_ENTRYPOINTS_HTTPS_FORWARDEDHEADERS_TRUSTEDIPS: ${CLOUDFLARE_IPS}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.tls: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.janejeon.com`)
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.middlewares: sso-proxy@file
      traefik.http.services.api@internal.loadbalancer.server.port: 8080
      flame.type: application
      flame.name: Traefik
      flame.url: traefik.janejeon.com
      flame.icon: server-network

networks:
  public:
    external: true
