version: '3'

services:
  traefik:
    image: traefik:v2.9.8
    container_name: traefik
    restart: unless-stopped
    healthcheck:
      # Not sure why I need to enable --ping here again
      test: traefik healthcheck --ping
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    command:
      - --configFile=/etc/traefik/static.yml
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik-data:/mnt/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/reverse-proxy/traefik.static.yml:/etc/traefik/static.yml:ro
      - ./services/reverse-proxy/traefik.dynamic.yml:/etc/traefik/dynamic.yml:ro
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      CF_ZONE_API_TOKEN: ${CF_ZONE_API_TOKEN}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.tls.certresolver: letsencrypt
      traefik.http.routers.traefik.rule: Host(`traefik.janejeon.com`)
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.middlewares: sso-proxy@file
      traefik.http.services.api@internal.loadbalancer.server.port: 8080
      flame.type: application
      flame.name: Traefik
      flame.url: traefik.janejeon.com
      flame.icon: routes

networks:
  public: {}

volumes:
  traefik-data: {}
