version: '3'

services:
  traefik:
    image: traefik:v2.6.3
    container_name: traefik
    restart: unless-stopped
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/reverse-proxy/traefik.static.yml:/etc/traefik/traefik.yml:ro
      - ./services/reverse-proxy/traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml:ro
      - ./volumes/certs:/etc/letsencrypt:ro # docker doesn't really handle symlinks
    environment:
      # Trust headers forwarded from Cloudflare to get accurate X-Forwarded-* information:
      # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
      TRAEFIK_ENTRYPOINTS_web-secure_FORWARDEDHEADERS_TRUSTEDIPS: 103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/13,104.24.0.0/14,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2405:8100::/32,2405:b500::/32,2606:4700::/32,2803:f800::/32,2a06:98c0::/29,2c0f:f248::/32
      TRAEFIK_ENTRYPOINTS_WEB-SECURE_FORWARDEDHEADERS_TRUSTEDIPS: ${CLOUDFLARE_IPS}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.tls: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.janejeon.com`)
      traefik.http.routers.traefik.entrypoints: web-secure
      traefik.http.routers.traefik.middlewares: sso-proxy@file
      traefik.http.services.api@internal.loadbalancer.server.port: 8080
      flame.type: application
      flame.name: Traefik
      flame.url: traefik.janejeon.com
      flame.icon: server-network

networks:
  public:
    external: true
