# static configuration
# see: https://doc.traefik.io/traefik/reference/static-configuration/file/
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

accessLog:
  format: common

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: :443
    http:
      middlewares:
        - gzip@file
        - no-www@file

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: public
  file:
    watch: true
    filename: /etc/traefik/traefik.dynamic.yml
