# static configuration
# see: https://doc.traefik.io/traefik/reference/static-configuration/file/
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

accessLog:
  format: common

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: :443
    http:
      middlewares:
        - gzip@file
        - no-www@file
    # Trust headers forwarded from Cloudflare to get accurate X-Forwarded-* information:
    # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
    forwardedHeaders:
      trustedIPs:
        # From: https://www.cloudflare.com/ips
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: public
  file:
    watch: true
    filename: /etc/traefik/traefik.dynamic.yml
