version: '3'

services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    restart: always
    networks:
      - private
    environment:
      APPRISE_STATELESS_URLS: sendgrid://${SENDGRID_API_KEY}:bot@janejeon.dev/${SLACK_ENDPOINT}
      APPRISE_STATEFUL_MODE: disabled
