version: '3'

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    networks:
      - public
    volumes:
      - ./volumes/adguardhome/work:/opt/adguardhome/work
      - ./volumes/adguardhome/conf:/opt/adguardhome/conf
    labels:
      traefik.enable: 'true'
      traefik.http.routers.adguard.tls: 'true'
      traefik.http.routers.adguard.rule: Host(`adguard.janejeon.com`)
      traefik.http.routers.adguard.middlewares: sso-proxy@file # use Authelia to authenticate AdGuard admin panel users
      traefik.http.services.adguard.loadbalancer.server.port: 80
      traefik.tcp.routers.adguard-dot.tls: 'true'
      traefik.tcp.routers.adguard-dot.rule: HostSNI(`adguard.janejeon.com`)
      traefik.tcp.routers.adguard-dot.entrypoints: dns-over-tls
      traefik.tcp.services.adguard-dot.loadbalancer.server.port: 53
      com.centurylinklabs.watchtower.enable: 'true'
      flame.type: application
      flame.name: AdguardHome
      flame.url: adguard.janejeon.com
      flame.icon: shield-link-variant

networks:
  public:
    external: true
