version: '3'

services:
  hoyocal:
    image: ghcr.io/janejeon/hoyocal:latest
    container_name: hoyocal-server
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/healthz || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - public
      - private
    environment:
      REDIS_URL: redis://redis:6379
      HOST: cal.${HOYO_HOST}
      SENTRY_DSN: ${SENTRY_DSN_HOYOCAL}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.hoyocal.tls.certresolver: letsencrypt
      traefik.http.routers.hoyocal.rule: Host(`cal.${HOYO_HOST}`)
      traefik.http.services.hoyocal.loadbalancer.server.port: 3000

networks:
  public: {}
  private: {}
