version: '3'

services:
  hoyocal-server:
    image: ghcr.io/janejeon/hoyocal:9caba5fb33d7ef370e0b64a73b38824c232062da
    container_name: hoyocal-server
    command: ['node', './dist/server/index.js']
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/healthz || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - public
      - private
    environment: &env
      REDIS_URL: redis://redis:6379
      APPRISE_URL: http://apprise:8000
      NTFY_URL: ${NTFY_URL}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.hoyocal-public.tls.certresolver: letsencrypt
      traefik.http.routers.hoyocal-public.rule: Host(`cal.${HOYO_HOST}`)
      traefik.http.services.hoyocal-public.loadbalancer.server.port: 3000
  hoyocal-worker:
    image: ghcr.io/janejeon/hoyocal:9caba5fb33d7ef370e0b64a73b38824c232062da
    container_name: hoyocal-worker
    command: ['node', './dist/worker/index.js']
    restart: unless-stopped
    networks:
      - private
    environment: *env

networks:
  public: {}
  private: {}
