version: '3'

services:
  whoogle:
    container_name: whoogle
    image: benbusby/whoogle-search:0.7.3
    restart: unless-stopped
    networks:
      - public
    environment:
      WHOOGLE_RESULTS_PER_PAGE: 25
      WHOOGLE_CONFIG_DISABLE: 1
      WHOOGLE_CONFIG_COUNTRY: US
      WHOOGLE_CONFIG_LANGUAGE: lang_en
      WHOOGLE_CONFIG_SEARCH_LANGUAGE: lang_en
      WHOOGLE_CONFIG_BLOCK: pinterest.com
      WHOOGLE_CONFIG_THEME: system
      WHOOGLE_CONFIG_VIEW_IMAGE: 1
      WHOOGLE_CONFIG_GET_ONLY: 1
      WHOOGLE_CONFIG_URL: whoogle.janejeon.com
    labels:
      traefik.enable: 'true'
      traefik.http.routers.whoogle.tls: 'true'
      traefik.http.routers.whoogle.rule: Host(`google.janejeon.com`)
      traefik.http.routers.whoogle.entrypoints: https
      traefik.http.routers.whoogle.middlewares: sso-proxy@file
      traefik.http.services.whoogle.loadbalancer.server.port: 5000
      flame.type: application
      flame.name: Whoogle
      flame.url: google.janejeon.com
      flame.icon: magnify

networks:
  public:
    external: true
