version: '3'

services:
  lldap:
    image: nitnelave/lldap:v0.4.1
    container_name: lldap
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:17170/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - public
    volumes:
      - lldap-data:/data
      - ./services/sso/config.toml:/data/lldap_config.toml:ro
    environment:
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_LDAP_USER_PASS: ${LLDAP_LDAP_USER_PASS}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.lldap.tls.certresolver: letsencrypt
      traefik.http.routers.lldap.rule: Host(`ldap.janejeon.com`)
      traefik.http.routers.lldap.entrypoints: https
      traefik.http.routers.lldap.middlewares: sso-proxy@file # if anything, for the forced 2FA
      traefik.http.services.lldap.loadbalancer.server.port: 17170
      flame.type: application
      flame.name: LLDAP
      flame.url: ldap.janejeon.com
      flame.icon: badge-account-horizontal-outline

networks:
  public: {}

volumes:
  lldap-data: {}
