version: '3'

services:
  lldap:
    image: nitnelave/lldap:v0.2.0
    container_name: lldap
    restart: unless-stopped
    init: true
    networks:
      - public
    volumes:
      - ./volumes/lldap:/data
      - ./services/sso/config.toml:/data/lldap_config.toml:ro
    environment:
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_LDAP_USER_PASS: ${LLDAP_LDAP_USER_PASS}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.lldap.tls: 'true'
      traefik.http.routers.lldap.rule: Host(`ldap.janejeon.com`)
      traefik.http.routers.lldap.entrypoints: web-secure
      traefik.http.routers.lldap.middlewares: sso-proxy@file # if anything, for the forced 2FA
      traefik.http.services.lldap.loadbalancer.server.port: 17170
      flame.type: application
      flame.name: LLDAP
      flame.url: ldap.janejeon.com
      flame.icon: badge-account-horizontal-outline

networks:
  public:
    external: true
