version: "3"

services:
  traefik:
    image: traefik:2.5
    container_name: traefik
    restart: always
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.static.yml:/etc/traefik/traefik.yml:ro
      - ./traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml:ro
      - ./acme.json:/letsencrypt/acme.json
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.traefik.tls=true
    #   - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
    #   - traefik.http.services.api@internal.loadbalancer.server.port=8080

networks:
  public:
    external: true
