version: '3'

services:
  traefik:
    image: traefik:2.5
    container_name: traefik
    restart: unless-stopped
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/reverse-proxy/traefik.static.yml:/etc/traefik/traefik.yml:ro
      - ./config/reverse-proxy/traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml:ro
      - ./volumes/certs/live:/mnt/certs:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.tls: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.janejeon.com`)
      traefik.http.routers.traefik.middlewares: sso-proxy@file
      traefik.http.services.api@internal.loadbalancer.server.port: 8080
      com.centurylinklabs.watchtower.enable: 'true'
      flame.type: application
      flame.name: Traefik
      flame.url: traefik.janejeon.com
      flame.icon: server-network

networks:
  public:
    external: true
