version: '3'

services:
  traefik:
    image: traefik:2.5
    container_name: traefik
    restart: unless-stopped
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/reverse-proxy/traefik.static.yml:/etc/traefik/traefik.yml:ro
      - ./config/reverse-proxy/traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml:ro
      - ./config/reverse-proxy/acme.json:/letsencrypt/acme.json
      - ./traefik.userfile:/etc/traefik/traefik.userfile
    environment:
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      CLOUDFLARE_ZONE_API_TOKEN: ${CLOUDFLARE_ZONE_API_TOKEN}
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      CF_ZONE_API_TOKEN: ${CLOUDFLARE_ZONE_API_TOKEN}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.janejeon.com`)
      traefik.http.routers.traefik.tls.certresolver: letsencrypt
      traefik.http.routers.traefik.middlewares: sso-proxy@file
      traefik.http.services.api@internal.loadbalancer.server.port: 8080
      com.centurylinklabs.watchtower.enable: 'true'
      flame.type: application
      flame.name: Traefik
      flame.url: traefik.janejeon.com
      flame.icon: routes

networks:
  public:
    external: true
