# static configuration
# see: https://doc.traefik.io/traefik/reference/static-configuration/file/
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

accessLog:
  format: common

# TODO: properly authorize w/ oauth2-proxy
api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: contact@janejeon.dev
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true
          priority: 10

  web-secure:
    address: :443
    http:
      middlewares:
        - floc@file
        - gzip@file
        - no-www@file

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: public
  file:
    watch: true
    filename: /etc/traefik/traefik.dynamic.yml
