# static configuration
# see: https://doc.traefik.io/traefik/reference/static-configuration/file/
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  format: json

accessLog:
  format: json

# TODO: properly authorize w/ oauth2-proxy
api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: contact@janejeon.dev
      storage: /letsencrypt/acme.json
      tlsChallenge: true
      httpChallenge:
        # used during the challenge
        entryPoint: web

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: :443
    http:
      middlewares:
        - floc@file

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: public
  file:
    watch: true
    filename: /etc/traefik/traefik.dynamic.yml
