http:
  middlewares:
    floc:
      headers:
        customResponseHeaders:
          Permissions-Policy: interest-cohort=()
    gzip:
      compress: {}
    no-www: # stripping https://www.blah -> https://blah
      redirectRegex:
        regex: ^(?:https://)?(?:www\.)?(.+)
        replacement: https://${1}
        permanent: true
    sso-proxy:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://authelia.janejeon.com
        trustForwardHeader: true
        authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
