version: '3'

services:
  hoyolab-auto:
    image: ghcr.io/torikushiii/hoyolab-auto:latest
    container_name: hoyolab-auto
    restart: unless-stopped
    volumes:
      - ./services/checkin/config.json5:/app/config.json5:ro
    environment:
      TZ: America/Los_Angeles
