services:
  typesense:
    image: typesense/typesense:0.24.1
    container_name: typesense
    restart: on-failure
    command: '--config=/etc/typesense/typesense-server.ini'
    networks:
      - public
      - private
    volumes:
      - typesense-data:/data
      - typesense-backup:/backup
      - ./services/search/config.ini:/etc/typesense/typesense-server.ini:ro
      - ./services/search/restore.sh:/usr/local/bin/restore:ro # we have to run the restore script from this container!
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_ADMIN_API_KEY}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.typesense.tls.certresolver: letsencrypt
      traefik.http.routers.typesense.rule: Host(`search.janejeon.com`)
      traefik.http.routers.typesense.entrypoints: https
      # no sso-proxy middleware; the search instance is supposed to be public
      # TODO: tighten ratelimit once the dashboard is installed as a web
      # (so the traffic flows within the docker network and doesn't hit traefik)
      traefik.http.routers.typesense.middlewares: ratelimit-burst@file,ratelimit-window@file
      traefik.http.services.typesense.loadbalancer.server.port: 8108
      # TODO: flame link?
  # We need a separate container, as the typesense image itself doesn't have tools like curl/wget,
  # which is needed to perform backup (not restore - see above; in fact, we can't even run restore
  # from this container *even if we wanted to*, because this container doesn't have the correct permissions
  # to run `cp`).
  # Therefore, we use this (persistent) container to run commands on behalf of typesense,
  # and keep the dead container around during normal operations.
  typesense-helper:
    image: curlimages/curl:8.00.1
    container_name: typesense-helper
    restart: on-failure
    # keep this alive indefinitely, so we can refer to this by the container name from the backup script
    entrypoint: tail
    command: -f /dev/null
    init: true
    networks:
      - private
    volumes:
      - typesense-data:/data
      - typesense-backup:/backup
      - ./services/search/dump.sh:/usr/local/bin/dump:ro
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_ADMIN_API_KEY}

networks:
  public: {}
  private: {} # private network is used just for typesense and typesense-helper to talk to each other

volumes:
  typesense-data: {}
  typesense-backup: {}
