version: '3'

services:
  backup:
    image: mazzolino/restic:1.7.0
    container_name: restic-backup
    restart: unless-stopped
    networks:
      - private
    hostname: docker
    volumes:
      - ./services/backup/excludes.txt:/etc/restic/excludes.txt
      - ./scripts/wait-for:/usr/local/bin/wait-for:ro
      - /var/lib/docker/volumes:/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUN_ON_STARTUP: 'true'
      BACKUP_CRON: '0 30 3 * * *'
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /docker/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude-file=/etc/restic/excludes.txt
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: ${TIMEZONE}
      # global context, can run anywhere within docker network
      # TODO: instead of using "healthchecks at home", just bake in the healthchecks as commands
      # within the respective docker containers, and call them.
      # e.g. timeout 1 bash -c 'while :; do echo check; sleep 0.1; done ' && echo "Do stuff" || echo 'Boo'
      PRE_COMMANDS: |-
        wait-for redis:6379 --timeout=60 -- docker exec redis dump
        wait-for mysql:3306 --timeout=60 -- docker exec mysql dump
        wait-for typesense:8108 --timeout=60 -- docker exec typesense-helper /usr/bin/local/dump
        docker exec uptime-kuma sh -c 'rm -f data/*.db.bak*'
      POST_COMMANDS_SUCCESS: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text": "Backup ran successfully!"}'' ${SLACK_NOTIFICATIONS_ENDPOINT}'
      POST_COMMANDS_FAILURE: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text": "Backup failed!"}'' ${SLACK_ALERTS_ENDPOINT}'

  prune:
    image: mazzolino/restic:1.7.0
    container_name: restic-prune
    restart: unless-stopped
    hostname: docker
    environment:
      RUN_ON_STARTUP: 'false'
      PRUNE_CRON: '0 0 4 * * *'
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: ${TIMEZONE}

  check:
    image: mazzolino/restic:1.7.0
    container_name: restic-check
    restart: unless-stopped
    hostname: docker
    environment:
      RUN_ON_STARTUP: 'false'
      CHECK_CRON: '0 30 4 * * *'
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: b2:${B2_BUCKET}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      TZ: ${TIMEZONE}

networks:
  private: {}
