version: '3'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.20
    container_name: adguardhome
    restart: unless-stopped
    networks:
      - public
    volumes:
      - ./volumes/adguardhome/work:/opt/adguardhome/work
      - ./volumes/adguardhome/conf:/opt/adguardhome/conf
    labels:
      traefik.enable: 'true'
      traefik.http.routers.adguard.tls: 'true'
      traefik.http.routers.adguard.rule: Host(`adguard.janejeon.com`)
      traefik.http.routers.adguard.entrypoints: https
      traefik.http.routers.adguard.middlewares: sso-proxy@file
      traefik.http.services.adguard.loadbalancer.server.port: 3000
      flame.type: application
      flame.name: AdguardHome
      flame.url: adguard.janejeon.com
      flame.icon: shield-link-variant-outline

networks:
  public:
    external: true
