version: '3'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.48
    container_name: adguardhome
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - public
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    labels:
      traefik.enable: 'true'
      traefik.http.routers.adguard.tls.certresolver: letsencrypt
      traefik.http.routers.adguard.rule: Host(`dns.${BASE_HOST}`)
      traefik.http.routers.adguard.middlewares: sso-proxy@file
      traefik.http.services.adguard.loadbalancer.server.port: 3000
      flame.type: application
      flame.name: AdguardHome
      flame.url: dns.${BASE_HOST}
      flame.icon: shield-link-variant-outline

networks:
  public: {}

volumes:
  adguard-work: {}
  adguard-conf: {}
