version: '3'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      - private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_INCLUDE_STOPPED: 'true'
      WATCHTOWER_LABEL_ENABLE: 'true'
      WATCHTOWER_LIFECYCLE_HOOKS: 'true'
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${SLACK_NOTIFICATIONS_ENDPOINT}
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
      com.centurylinklabs.watchtower.monitor-only: 'true'

networks:
  private:
    external: true
