version: '3'

services:
  flame:
    image: pawelmalak/flame:2.3.0
    container_name: flame
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5005 || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - public
    volumes:
      - ./volumes/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PASSWORD: ''
    labels:
      traefik.enable: 'true'
      traefik.http.routers.homepage.tls.certresolver: letsencrypt
      traefik.http.routers.homepage.rule: Host(`home.janejeon.com`)
      traefik.http.routers.homepage.entrypoints: https
      traefik.http.routers.homepage.middlewares: sso-proxy@file
      traefik.http.services.homepage.loadbalancer.server.port: 5005

networks:
  public: {}
