version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      - private
    expose:
      - 3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./volumes/dumps:/mnt/dumps
      - ./config/database/init:/docker-entrypoint-initdb.d
      - ./config/database/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-password
    cap_add:
      - SYS_NICE
    labels:
      com.datadoghq.ad.check_names: '["mysql"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"server": "mysql", "user": "datadog", "pass": "datadog-password"}]'

networks:
  private:
    external: true
