version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      - private
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./volumes/dumps:/mnt/dumps
      - ./config/database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-password
    cap_add:
      - SYS_NICE

networks:
  private:
    external: true
