version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      - private
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-password

networks:
  private:
    external: true

volumes:
  mysql_data:
