version: '3'

services:
  authelia:
    image: authelia/authelia:4.38.0
    container_name: authelia
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      lldap:
        condition: service_healthy
    networks:
      - public
      - private
    volumes:
      - ./services/sso-proxy/config.yml:/config/configuration.yml:ro
    environment:
      AUTHELIA_NOTIFIER_SMTP_SENDER: ${SMTP_SENDER}
      AUTHELIA_NOTIFIER_SMTP_USERNAME: ${SMTP_USER}
      AUTHELIA_NOTIFIER_SMTP_PASSWORD: ${SMTP_PASS}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${LLDAP_LDAP_USER_PASS}
      TZ: ${TIMEZONE}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.authelia.tls.certresolver: letsencrypt
      traefik.http.routers.authelia.rule: Host(`auth.janejeon.com`)
      traefik.http.routers.authelia.entrypoints: https
      traefik.http.routers.authelia.middlewares: sso-proxy@file
      traefik.http.services.authelia.loadbalancer.server.port: 9091
      flame.type: application
      flame.name: Authelia
      flame.url: auth.janejeon.com
      flame.icon: shield-account-variant-outline

networks:
  public: {}
  private: {}
