version: '3'

services:
  authelia:
    image: authelia/authelia:4.38.18
    container_name: authelia
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      lldap:
        condition: service_healthy
    networks:
      - public
      - private
    volumes:
      - ./services/sso-proxy/config.yml:/config/configuration.yml:ro
    environment:
      TZ: ${TIMEZONE}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.authelia.tls.certresolver: letsencrypt
      traefik.http.routers.authelia.rule: Host(`auth.${BASE_HOST}`)
      traefik.http.routers.authelia.middlewares: sso-proxy@file
      traefik.http.services.authelia.loadbalancer.server.port: 9091

networks:
  public: {}
  private: {}
