version: '3'

services:
  authelia:
    image: authelia/authelia:4.35.0
    container_name: authelia
    restart: unless-stopped
    entrypoint:
      - wait-for
      - mysql:3306
      - --timeout=60
      - --
      - /app/entrypoint.sh
    command:
      - --config
      - /etc/authelia/config.yml
    networks:
      - public
      - private
    volumes:
      - ./scripts/wait-for:/usr/local/bin/wait-for:ro
      - ./services/sso-proxy/config.yml:/etc/authelia/config.yml:ro
    environment:
      AUTHELIA_NOTIFIER_SMTP_SENDER: ${SMTP_SENDER}
      AUTHELIA_NOTIFIER_SMTP_USERNAME: ${SMTP_USER}
      AUTHELIA_NOTIFIER_SMTP_PASSWORD: ${SMTP_PASS}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${LLDAP_LDAP_USER_PASS}
      TZ: ${TIMEZONE}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.authelia.tls: 'true'
      traefik.http.routers.authelia.rule: Host(`auth.janejeon.com`)
      traefik.http.routers.authelia.entrypoints: web-secure
      traefik.http.routers.authelia.middlewares: sso-proxy@file
      traefik.http.services.authelia.loadbalancer.server.port: 9091
      flame.type: application
      flame.name: Authelia
      flame.url: auth.janejeon.com
      flame.icon: shield-account-variant-outline

networks:
  public:
    external: true
  private:
    external: true
