version: '3'

services:
  gc:
    image: yelp/docker-custodian:0.7.4
    container_name: gc
    command:
      - --max-container-age
      - 7days
      - --max-image-age
      - 30days
      - --dangling-volumes
      - --exclude-container-label
      - dcgc.keep-container=true
    networks:
      - private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  private: {}
