version: '3'

services:
  devblog:
    image: ghost:4.36.0-alpine
    container_name: ghost-devblog
    restart: unless-stopped
    entrypoint:
      - wait-for
      - mysql:3306
      - --timeout=60
      - --
      - docker-entrypoint.sh
    command:
      - node
      - current/index.js
    networks:
      - public
      - private
    volumes:
      - ./volumes/ghost/janejeon.dev:/var/lib/ghost/content
      - ./config/blog/themes/journal:/var/lib/ghost/content/themes/journal:ro
      - ./scripts/wait-for:/usr/local/bin/wait-for:ro
      - ./config/blog/config.json:/var/lib/ghost/config.production.json:ro
    environment:
      url: https://janejeon.dev
      database__connection__user: ghost-devblog
      database__connection__password: ghost-devblog-password
      database__connection__database: devblog
      mail__from: ${SMTP_SENDER}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASS}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.devblog.tls: 'true'
      traefik.http.routers.devblog.rule: Host(`janejeon.dev`)
      traefik.http.routers.devblog.entrypoints: web-secure
      traefik.http.services.devblog.loadbalancer.server.port: 2368
      flame.type: application
      flame.name: Ghost - Blog
      flame.url: janejeon.dev
      flame.icon: ghost

  portfolio:
    image: ghost:4.36.0-alpine
    container_name: ghost-portfolio
    restart: unless-stopped
    entrypoint:
      - wait-for
      - mysql:3306
      - --timeout=60
      - --
      - docker-entrypoint.sh
    command:
      - node
      - current/index.js
    networks:
      - public
      - private
    volumes:
      - ./volumes/ghost/nariahn.com:/var/lib/ghost/content
      - ./config/blog/themes/london:/var/lib/ghost/content/themes/london:ro
      - ./scripts/wait-for:/usr/local/bin/wait-for:ro
      - ./config/blog/config.json:/var/lib/ghost/config.production.json:ro
    environment:
      url: https://nariahn.com
      database__client: mysql
      database__connection__user: ghost-portfolio
      database__connection__password: ghost-portfolio-password
      database__connection__database: portfolio
      mail__from: ${SMTP_SENDER}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASS}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.portfolio.tls: 'true'
      traefik.http.routers.portfolio.rule: Host(`nariahn.com`)
      traefik.http.routers.portfolio.entrypoints: web-secure
      traefik.http.services.portfolio.loadbalancer.server.port: 2368
      flame.type: application
      flame.name: Ghost - Portfolio
      flame.url: nariahn.com
      flame.icon: ghost

networks:
  public:
    external: true
  private:
    external: true
