version: '3'

services:
  whoami:
    image: traefik/whoami:v1.10.3
    container_name: whoami
    restart: unless-stopped
    networks:
      - public
    labels:
      traefik.enable: 'true'
      traefik.http.routers.whoami.tls.certresolver: letsencrypt
      traefik.http.routers.whoami.rule: Host(`whoami.${BASE_HOST}`)
      # traefik.http.routers.whoami.middlewares: sso-proxy@file
      traefik.http.services.whoami.loadbalancer.server.port: 80

networks:
  public: {}
