version: '3'

services:
  whoami:
    image: traefik/whoami:v1.10.1
    container_name: whoami
    restart: unless-stopped
    networks:
      - public
    labels:
      traefik.enable: 'true'
      traefik.http.routers.whoami.tls.certresolver: letsencrypt
      traefik.http.routers.whoami.rule: Host(`whoami.janejeon.com`)
      traefik.http.routers.whoami.entrypoints: https
      # traefik.http.routers.whoami.middlewares: sso-proxy@file
      traefik.http.services.whoami.loadbalancer.server.port: 8080 # they changed the fackin' ports, why
      flame.type: application
      flame.name: Whoami
      flame.url: whoami.janejeon.com
      flame.icon: mirror-rectangle

networks:
  public: {}
