version: '3'

services:
  change-detection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.48.04
    container_name: change-detection
    restart: unless-stopped
    networks:
      - public
    volumes:
      - change-detection-datastore:/datastore
    environment:
      BASE_URL: https://change-detection.${BASE_HOST}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.change-detection.tls.certresolver: letsencrypt
      traefik.http.routers.change-detection.rule: Host(`change-detection.${BASE_HOST}`)
      traefik.http.routers.change-detection.middlewares: sso-proxy@file
      traefik.http.services.change-detection.loadbalancer.server.port: 5000

networks:
  public: {}

volumes:
  change-detection-datastore: {}
