version: '3'

services:
  change-detection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.45.14
    container_name: change-detection
    restart: unless-stopped
    networks:
      - public
    volumes:
      - change-detection-datastore:/datastore
    environment:
      BASE_URL: https://change-detection.janejeon.com
    labels:
      traefik.enable: 'true'
      traefik.http.routers.change-detection.tls.certresolver: letsencrypt
      traefik.http.routers.change-detection.rule: Host(`change-detection.janejeon.com`)
      traefik.http.routers.change-detection.entrypoints: https
      traefik.http.routers.change-detection.middlewares: sso-proxy@file
      traefik.http.services.change-detection.loadbalancer.server.port: 5000
      flame.type: application
      flame.name: ChangeDetection
      flame.url: change-detection.janejeon.com
      flame.icon: vector-difference-ba

networks:
  public: {}

volumes:
  change-detection-datastore: {}
