version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.16.0-alpine
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - public
      - private
    volumes:
      - ./volumes/uptime-kuma:/app/data
    labels:
      traefik.enable: 'true'
      traefik.http.routers.uptime-kuma.tls: 'true'
      traefik.http.routers.uptime-kuma.rule: Host(`up.janejeon.com`)
      traefik.http.routers.uptime-kuma.entrypoints: https
      traefik.http.routers.uptime-kuma.middlewares: sso-proxy@file
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
      flame.type: application
      flame.name: Uptime Kuma
      flame.url: up.janejeon.com/status
      flame.icon: swap-vertical

networks:
  public:
    external: true
  private:
    external: true
