version: "3"

services:
  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_PROCESS_AGENT_ENABLED: "true"
    labels:
      com.datadoghq.ad.check_names: '["ssh_check"]'
      com.datadoghq.ad.init_configs: "[{}]"
      com.datadoghq.ad.instances: '[{"host": "localhost", "port":"22", "username":"jane"}]'
