data_dir: /var/lib/vector

sources:
  docker_host_logs:
    type: docker_logs

sinks:
  grafana_cloud_loki:
    type: loki
    inputs: [docker_host_logs]
    endpoint: https://logs-prod-us-central1.grafana.net
    auth:
      strategy: basic
      user: '${GRAFANA_CLOUD_LOKI_USER}'
      password: ${GRAFANA_CLOUD_LOKI_PASS}
    labels:
      container: '{{ container_name }}'
      host: '{{ host }}'
      image: '{{ image }}'
      stream: '{{ stream }}'
    remove_label_fields: true
    encoding:
      codec: text
  new_relic_logs:
    type: new_relic_logs
    inputs: [docker_host_logs]
    license_key: ${NEW_RELIC_API_KEY}
    region: us
  elastic_cloud:
    type: elasticsearch
    inputs: [docker_host_logs]
    endpoint: ${ELASTICSEARCH_ENDPOINT}
    index: my-index
    auth:
      strategy: basic
      user: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
